runtime: go114

main: cmd/server

manual_scaling:
  instances: 1

handlers:
  - url: /api/.*
    script: auto
  - url: /(.*\..+)$ 
    static_files: frontend/dist/\1
    upload: frontend/dist/(.*\..+)$
  - url: /
    static_files: frontend/dist/index.html
    upload: frontend/dist/index\.html
  - url: /[^_].*
    static_files: frontend/dist/index.html
    upload: frontend/dist/index\.html
