name: pages-build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build files
      run: |
        cd frontend
        sed -i 's/history/hash/g' src/router/index.ts
        sed -i 's/""/"https:\/\/recomator-282910.ey.r.appspot.com"/g' src/config.ts
        npm ci
        npm run build
        sed -i 's/=\/js\//=js\//g' dist/index.html
        sed -i 's/=\/css\//=css\//g' dist/index.html
        mv dist/index.html ../index.html
        mv dist/css ../css
        mv dist/js ../js
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f index.html
        git add -f css
        git add -f js 
        git commit -am "Changes introduced in a github action"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'pages'
        force: 'true' 
